---
##
## this role obtains prefix information from netbox for the specified role, if it exists.  
##
    
    
- name: Debug output for obtaining prefix information from Netbox via role
  vars: 
    msg: |
         role:              {{ environment_lb }}
         netbox_headers:    {{ netbox_headers }}

  delegate_to: localhost
  tags: debugme
  debug:
    msg: "{{ msg.split('\n') }}"    
    

- name: Query Netbox prefixes API endpoint to check for the prefix entry that matches the VLAN and site specified
  uri:
    url: https://netbox.comms.yodel.net/api/ipam/prefixes/?role={{ environment_lb | default ('0') }}
    method: GET
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json 
    headers: "{{ netbox_headers }}"
    
  register: prefix_result
  delegate_to: localhost
  tags: [ 'netbox_get_prefix_from_role' ]
