---
##
## this role obtains prefix information from netbox for the specified VLAN, if it exists.  
##
    
    
- name: Debug output for obtaining prefix information from Netbox
  vars: 
    msg: |
         vlan_result:       {{ ip_result.json.results[0].address |  default('unspecified-ip-address') }}
         netbox_headers:    {{ netbox_headers }}

  delegate_to: localhost
  tags: debugme
  debug:
    msg: "{{ msg.split('\n') }}"    
    

- name: Query Netbox prefixes API endpoint to check for the prefix entries that contains the IP address
  uri:
    url: https://netbox.comms.yodel.net/api/ipam/prefixes/?contains={{ ip_result.json.results[0].address | default ('0') }}
    method: GET
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json 
    headers: "{{ netbox_headers }}"
    
  register: prefix_result
  delegate_to: localhost
  tags: [ 'netbox_get_prefix_from_ip' ]

