---
#
# this playbook deploys a load balanced application to a F5 BIG-IP device.
# the paramters used to deploy the application are taken from a combination of:
# - the specified hosts
# - the specified group_vars
# - the dictionary 'node_parameters_dict', assembled by previous playbooks that query the Netbox API.
#

- name: "Delete a load balanced application on a F5 BIG-IP device."
  hosts: "{{ group | default('undefined-hosts') }}"
  gather_facts: no
  tasks:

  - name: "Delete F5 BIG-IP virtual server for application: {{ group }}."
    import_role:
      name: f5_manage_virtual_server
    ignore_errors: yes
    tags: f5_delete_virtual_server


  - name: "Delete F5 BIG-IP virtual address for application: {{ group }}."
    import_role:
       name: f5_manage_virtual_address
    ignore_errors: yes
    tags: f5_delete_virtual_address


  - name: "Delete F5 BIG-IP pool(s) for application: {{ group }}."
    import_role:
      name: f5_manage_pool
    ignore_errors: yes
    tags: f5_delete_pool


  - name: "Delete F5 BIG-IP monitor(s) for application: {{ group }}."
    import_role:
      name: f5_manage_monitor
    ignore_errors: yes
    tags: f5_delete_monitor


  - name: "Delete F5 BIG-IP node(s) for application: {{ group }}."
    import_role:
      name: f5_manage_node
    ignore_errors: yes
    tags: f5_delete_node









