---
##
##  This role manages pool members on the F5 big-ip
##  Ref: https://docs.ansible.com/ansible/latest/modules/bigip_pool_member_module.html
##

- name: Debug output for pool membership management via FQDN
  vars: 
    msg: |
         node_name:         /{{ f5_partition }}/{{ inventory_hostname }}.yodel.net
         node_fqdn:         /{{ f5_partition }}/{{ inventory_hostname }}.yodel.net
         node_partition:    {{ f5_partition }}
         pool:              {{ node_parameters_dict[inventory_hostname|lower]['environment']+ '-' + hostvars[inventory_hostname]['group_names'][0] }}-{{ item.key }}_Pool
         pool_port:         {{ item.value.f5_pool_port | default(f5_defaults.f5_pool_port) }}
         pool_state:        {{ component_state }}
         provider:          {{ node_parameters_dict[inventory_hostname|lower]['f5_provider'] }}

  with_dict: "{{ f5_services }}"
  delegate_to: localhost
  tags: debugme
  debug:
    msg: "{{ msg.split('\n') }}"
  when: 
    - item.key is not search("http-redirect")


- name: "Manage F5 BIG-IP pool node membership for application: {{ group }}  {{ play_hosts }}"
  bigip_pool_member:
    name:         "/{{ f5_partition }}/{{ inventory_hostname|lower }}.yodel.net"
    fqdn:         "/{{ f5_partition }}/{{ inventory_hostname|lower }}.yodel.net"
    partition:    "{{ f5_partition }}"
    pool:         "{{ node_parameters_dict[inventory_hostname|lower]['environment']+ '-' + hostvars[inventory_hostname]['group_names'][0] }}-{{ item.key }}_Pool"
    port:         "{{ item.value.f5_pool_port | default(f5_defaults.f5_pool_port) }}"
    state:        "{{ component_state }}"
    provider:     "{{ node_parameters_dict[inventory_hostname|lower]['f5_provider'] }}"
    
  delegate_to: localhost
  with_dict: "{{ f5_services }}"
  tags: [ 'f5_manage_pool_members' ]
  when: 
    - item.key is not search("http-redirect")
    - environment_lb is not search("web")


- name: "Manage F5 BIG-IP pool web node membership for application: {{ group }}  {{ play_hosts }}"
  bigip_pool_member:
    name:         "/{{ f5_partition }}/{{ inventory_hostname|lower }}-fe.yodel.net"
    fqdn:         "/{{ f5_partition }}/{{ inventory_hostname|lower }}-fe.yodel.net"
    partition:    "{{ f5_partition }}"
    pool:         "{{ node_parameters_dict[inventory_hostname|lower]['environment']+ '-' + hostvars[inventory_hostname]['group_names'][0] }}-{{ item.key }}_Pool"
    port:         "{{ item.value.f5_pool_port | default(f5_defaults.f5_pool_port) }}"
    state:        "{{ component_state }}"
    provider:     "{{ node_parameters_dict[inventory_hostname|lower]['f5_provider'] }}"
    
  delegate_to: localhost
  with_dict: "{{ f5_services }}"
  tags: [ 'f5_manage_pool_members' ]
  when: 
    - item.key is not search("http-redirect")
    - environment_lb is search("web")


